### ISSUE TITLE
Aspect Ratio fails on Portrait Cameras

### ISSUE THREAD

**Issue by cakeller98** [EatTheFuture/camera_projector#1]
When using a portrait oriented image e.g. 9:16 instead of 16:9, the aspect nodes cause improper scaling.

![2023-02-20_17h24_12](https://user-images.githubusercontent.com/203922/220224818-ba4fab6a-9f2d-4386-8bca-57d6361249c2.jpg)

The solution above seems to solve it for any orientation. it assigns the aspect if greater than 1 to y aspect and 1/aspect if greater than 1 to x aspect. If either value is not greater than 1, then it is assigned 1.

let me know if this doesn't cause any other issues, and if you want me to push the updated script. 

Thanks for this script by the way, it's great!

**Comment by cessen** [comment]
When did you download the addon?  I believe this has already been fixed since Dec 21st 2022.  Unless I'm misunderstanding the issue.

**Comment by cakeller98** [comment]
Downloaded on 12/19.  Missed that it had been updated. (version not bumped still (0,1,0) 
Seems like the same fix - slightly different nodes. ;-)
